/**
 * Hash routing.
 *
 * Every operation and every schema is addressable, so a link to one can be
 * pasted into a ticket, and the browser's back button does what it looks like
 * it does. Filters ride along in the query part so a filtered view is
 * shareable too.
 *
 *   #/op/post-v2-bookings?tag=Bookings&verb=POST&q=book&deprecated=hide
 *   #/schema/Booking
 *   #/import
 *
 * A schema can also be named in the query string, before the fragment, which
 * is the shape a link handed out by someone else usually takes:
 *
 *   ?url=https://api.example.com/openapi.yaml
 */

/** @returns {{view: string, id: string|null, filters: object}} */
export function parseHash(hash = globalThis.location?.hash ?? '') {
  const raw = String(hash).replace(/^#/, '');
  const [pathPart, queryPart] = raw.split('?');
  const segments = pathPart.split('/').filter(Boolean);
  const params = new URLSearchParams(queryPart ?? '');

  // `src` is not a filter: it is the schema the rest of the URL is about, so a
  // link to an operation in a public schema opens that operation for someone
  // who has never loaded it.
  const src = params.get('src');

  const filters = {
    query: params.get('q') ?? '',
    tags: params.getAll('tag'),
    verbs: params.getAll('verb').map((v) => v.toUpperCase()),
    scopes: params.getAll('scope'),
    statusCodes: params.getAll('status'),
    hideDeprecated: params.get('deprecated') === 'hide',
    onlyDeprecated: params.get('deprecated') === 'only',
  };

  if (segments[0] === 'op' && segments[1]) {
    return { view: 'operation', id: decodeURIComponent(segments[1]), filters, src };
  }
  if (segments[0] === 'schema' && segments[1]) {
    return { view: 'schema', id: decodeURIComponent(segments[1]), filters, src };
  }
  if (segments[0] === 'import') return { view: 'import', id: null, filters, src: null };
  return { view: 'browse', id: null, filters, src };
}

/** Build a hash for a target plus the current filters. */
export function buildHash({ view, id, filters, src }) {
  const params = new URLSearchParams();
  if (src) params.set('src', src);
  if (filters?.query) params.set('q', filters.query);
  for (const tag of filters?.tags ?? []) params.append('tag', tag);
  for (const verb of filters?.verbs ?? []) params.append('verb', verb);
  for (const scope of filters?.scopes ?? []) params.append('scope', scope);
  for (const code of filters?.statusCodes ?? []) params.append('status', code);
  if (filters?.hideDeprecated) params.set('deprecated', 'hide');
  else if (filters?.onlyDeprecated) params.set('deprecated', 'only');
  const query = params.toString();

  let path = '/';
  if (view === 'operation' && id) path = `/op/${encodeURIComponent(id)}`;
  else if (view === 'schema' && id) path = `/schema/${encodeURIComponent(id)}`;
  else if (view === 'import') path = '/import';

  return `#${path}${query ? `?${query}` : ''}`;
}

/**
 * Fold a schema named in the query string into the fragment.
 *
 * `#…?src=` is how allyway addresses a document internally, and it has to be
 * in the fragment because that is where the rest of the address lives — which
 * operation is open, which filters are on. But a link written by hand, or
 * generated by something else, is far likelier to be `?url=…` on the end of
 * the origin: that is what a query string looks like everywhere else, and it
 * survives being pasted into the many things that treat a fragment as noise.
 *
 * So both spellings are taken at the door and rewritten to the one the app
 * reads, rather than teaching every caller to look in two places. `src` is
 * accepted here too, because someone who has seen the fragment form will try
 * it. A `src` already in the fragment wins: it is the more specific answer,
 * arriving with the operation it wants open.
 *
 * @param {string} href the current address
 * @returns {string|null} the address to replace it with, or null for nothing to do
 */
export function foldQuerySchema(href) {
  let url;
  try {
    url = new URL(href);
  } catch {
    return null;
  }
  const named = url.searchParams.get('url') ?? url.searchParams.get('src');
  if (!named) return null;

  url.searchParams.delete('url');
  url.searchParams.delete('src');
  const route = parseHash(url.hash);
  url.hash = buildHash({
    view: route.view,
    id: route.id,
    filters: route.filters,
    src: route.src ?? named,
  });
  return url.toString();
}

export class Router {
  #handler;
  #suppress = false;

  /** @param {(route: object) => void} handler */
  constructor(handler) {
    this.#handler = handler;
    globalThis.addEventListener('hashchange', () => {
      if (this.#suppress) {
        this.#suppress = false;
        return;
      }
      this.#handler(parseHash());
    });
  }

  /** Read the URL now. */
  start() {
    this.#handler(parseHash());
  }

  /**
   * Push a new URL without re-entering the handler — the caller has already
   * applied the state change that prompted it.
   * @param {{view: string, id?: string|null, filters?: object}} target
   * @param {{replace?: boolean}} [options]
   */
  go(target, options = {}) {
    const hash = buildHash(target);
    if (hash === globalThis.location.hash) return;
    this.#suppress = true;
    if (options.replace) {
      globalThis.history.replaceState(null, '', hash);
      this.#suppress = false;
    } else {
      globalThis.location.hash = hash;
    }
  }
}
